## Importing Libraries

In [48]:
import pandas as pd
import numpy as np
import ast

## Cleaning

In [49]:
with open('Dataset/games.csv', encoding='utf-8') as f:
    s = f.read()

with open('Dataset/games_Fixed.csv', 'w', encoding='utf-8') as f:
    f.write(s.replace('DiscountDLC', 'Discount,DLC', 1))

In [50]:
df = pd.read_csv('Dataset/games_Fixed.csv')

df.head(5)

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,Discount,DLC count,About the game,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
0,20200,Galactic Bowling,"Oct 21, 2008",0 - 20000,0,0,19.99,0,0,Galactic Bowling is an exaggerated and stylize...,...,0,0,0,Perpetual FX Creative,Perpetual FX Creative,"Single-player,Multi-player,Steam Achievements,...","Casual,Indie,Sports","Indie,Casual,Sports,Bowling",https://cdn.akamai.steamstatic.com/steam/apps/...,http://cdn.akamai.steamstatic.com/steam/apps/2...
1,655370,Train Bandit,"Oct 12, 2017",0 - 20000,0,0,0.99,0,0,THE LAW!! Looks to be a showdown atop a train....,...,0,0,0,Rusty Moyher,Wild Rooster,"Single-player,Steam Achievements,Full controll...","Action,Indie","Indie,Action,Pixel Graphics,2D,Retro,Arcade,Sc...",https://cdn.akamai.steamstatic.com/steam/apps/...,http://cdn.akamai.steamstatic.com/steam/apps/2...
2,1732930,Jolt Project,"Nov 17, 2021",0 - 20000,0,0,4.99,0,0,Jolt Project: The army now has a new robotics ...,...,0,0,0,Campião Games,Campião Games,Single-player,"Action,Adventure,Indie,Strategy",NaN,https://cdn.akamai.steamstatic.com/steam/apps/...,http://cdn.akamai.steamstatic.com/steam/apps/2...
3,1355720,Henosis™,"Jul 23, 2020",0 - 20000,0,0,5.99,0,0,HENOSIS™ is a mysterious 2D Platform Puzzler w...,...,0,0,0,Odd Critter Games,Odd Critter Games,"Single-player,Full controller support","Adventure,Casual,Indie","2D Platformer,Atmospheric,Surreal,Mystery,Puzz...",https://cdn.akamai.steamstatic.com/steam/apps/...,http://cdn.akamai.steamstatic.com/steam/apps/2...
4,1139950,Two Weeks in Painland,"Feb 3, 2020",0 - 20000,0,0,0.00,0,0,ABOUT THE GAME Play as a hacker who has arrang...,...,0,0,0,Unusual Games,Unusual Games,"Single-player,Steam Achievements","Adventure,Indie","Indie,Adventure,Nudity,Violent,Sexual Content,...",https://cdn.akamai.steamstatic.com/steam/apps/...,http://cdn.akamai.steamstatic.com/steam/apps/2...

In [51]:
print("Info:")
print(df.info())

print("Missing Values:")
missing_values = df.isnull().sum()
display(missing_values[missing_values > 0].sort_values(ascending=False))

print("Basic Statistics:")
display(df.describe())

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97410 entries, 0 to 97409
Data columns (total 40 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   AppID                       97410 non-null  int64
 1   Name                        97404 non-null  object
 2   Release date                97410 non-null  object
 3   Estimated owners            97410 non-null  object
 4   Peak CCU                    97410 non-null  int64
 5   Required age                97410 non-null  int64
 6   Price                       97410 non-null  float64
 7   Discount                    97410 non-null  int64
 8   DLC count                   97410 non-null  int64
 9   About the game              92540 non-null  object
 10  Supported languages         97410 non-null  object
 11  Full audio languages        97410 non-null  object
 12  Reviews                     10125 non-null  object
 13  Header image                97410 non-null  object
 14  Website                     42737 non-null  object
 15  Support url                 45908 non-null  object
 16  Support email               81378 non-null  object
 17  Windows                     97410 non-null  bool
 18  Mac                         97410 non-null  bool
 19  Linux                       97410 non-null  bool
 20  Metacritic score            97410 non-null  int64
 21  Metacritic url              3953 non-null   object
 22  User score                  97410 non-null  int64
 23  Positive                    97410 non-null  int64
 24  Negative                    97410 non-null  int64
 25  Score rank                  44 non-null     float64
 26  Achievements                97410 non-null  int64
 27  Recommendations             97410 non-null  int64
 28  Notes                       15474 non-null  object
 29  Average playtime forever    97410 non-null  int64
 30  Average playtime two weeks  97410 non-null  int64
 31  Median playtime forever     97410 non-null  int64
 32  Median playtime two weeks   97410 non-null  int64
 33  Developers                  92534 non-null  object
 34  Publishers                  92274 non-null  object
 35  Categories                  91497 non-null  object
 36  Genres                      92569 non-null  object
 37  Tags                        67647 non-null  object
 38  Screenshots                 94515 non-null  object
 39  Movies                      89519 non-null  object
dtypes: bool(3), float64(2), int64(15), object(20)
memory usage: 27.8+ MB
None
Missing Values:

Score rank        97366
Metacritic url    93457
Reviews           87285
Notes             81936
Website           54673
Support url       51502
Tags              29763
Support email     16032
Movies             7891
Categories         5913
Publishers         5136
Developers         4876
About the game     4870
Genres             4841
Screenshots        2895
Name                  6
dtype: int64

Basic Statistics:

,AppID,Peak CCU,Required age,Price,Discount,DLC count,Metacritic score,User score,Positive,Negative,Score rank,Achievements,Recommendations,Average playtime forever,Average playtime two weeks,Median playtime forever,Median playtime two weeks
count,9.741000e+04,9.741000e+04,97410.000000,97410.000000,97410.0,97410.000000,97410.000000,97410.000000,9.741000e+04,97410.000000,44.000000,97410.000000,9.741000e+04,97410.000000,97410.000000,97410.000000,97410.000000
mean,1.524636e+06,1.627283e+02,0.282497,7.086262,0.0,0.493081,2.959193,0.034791,8.489366e+02,141.065989,98.909091,18.562622,6.905128e+02,91.797937,9.621271,81.852459,10.340417
std,8.001310e+05,7.687116e+03,2.144294,12.387782,0.0,12.832834,14.545462,1.674105,2.287011e+04,4278.019743,0.857747,160.413540,1.681717e+04,1068.494928,177.190210,1412.496536,192.711603
min,1.000000e+01,0.000000e+00,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000e+00,0.000000,97.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,8.477925e+05,0.000000e+00,0.000000,0.990000,0.0,0.000000,0.000000,0.000000,0.000000e+00,0.000000,98.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
50%,1.489990e+06,0.000000e+00,0.000000,4.190000,0.0,0.000000,0.000000,0.000000,5.000000e+00,1.000000,99.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
75%,2.180648e+06,1.000000e+00,0.000000,9.990000,0.0,0.000000,0.000000,0.000000,3.500000e+01,10.000000,100.000000,17.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
max,3.199580e+06,1.284268e+06,21.000000,999.980000,0.0,2366.000000,97.000000,100.000000,5.764420e+06,895978.000000,100.000000,9821.000000,3.441592e+06,145727.000000,19159.000000,208473.000000,19159.000000

In [52]:
columns_to_drop = [
    'Reviews', 'Metacritic url', 'Score rank', 'Notes', 'Metacritic score', # High NaNs
    'Website', 'Support url', 'Support email', # URLs/Emails
    'Header image', 'Screenshots', 'Movies', # Media links
    'Average playtime forever', 'Average playtime 2 weeks', 'Median playtime two weeks', # We plan to do analysis on median playtime forever, as large number of players not playing the game even though owning it would heavily skew the average making it unreliable
    'Discount', # No variance (always 0)
    'User score' # Unreliable (mostly 0)
]

df.drop(columns=columns_to_drop, inplace=True, errors='ignore')
print(f"Dropped {len(columns_to_drop)} columns.")

print(f"Remaining columns: {df.shape[1]}")
print("\nColumns after initial drop:")
print(df.columns.tolist())

print("Missing Values:")
missing_values = df.isnull().sum()
display(missing_values[missing_values > 0].sort_values(ascending=False))

drop_na_rows = [
    'Categories', 'Genres', 'Tags', # Since they are needed for analysis, we will drop rows with NaN values in these columns since can't infer anything from them
    'Publishers', 'Developers', # Also cannot infer anything from them being empty
    "About the game", # We plan to do NLP on this column, so we drop empty rows as well
]

print(f"Rows before dropping NaN: {df.shape[0]}")
df.dropna(subset=drop_na_rows, inplace=True)

print(f"Dropped {len(drop_na_rows)} columns with NaN values.")
print(f"Rows after dropping NaN: {df.shape[0]}")

print(f"New Shape: {df.shape}")

Dropped 16 columns.
Remaining columns: 25

Columns after initial drop:
['AppID', 'Name', 'Release date', 'Estimated owners', 'Peak CCU', 'Required age', 'Price', 'DLC count', 'About the game', 'Supported languages', 'Full audio languages', 'Windows', 'Mac', 'Linux', 'Positive', 'Negative', 'Achievements', 'Recommendations', 'Average playtime two weeks', 'Median playtime forever', 'Developers', 'Publishers', 'Categories', 'Genres', 'Tags']
Missing Values:

Tags              29763
Categories         5913
Publishers         5136
Developers         4876
About the game     4870
Genres             4841
Name                  6
dtype: int64

Rows before dropping NaN: 97410
Dropped 6 columns with NaN values.
Rows after dropping NaN: 66272
New Shape: (66272, 25)

### Feature Engineering

Converting the dates to date time, in order to convert them into game age for easier analysis

In [53]:
df['Release date'] = pd.to_datetime(df['Release date'], errors='coerce') # Converting to datetime for time series analysis

print(f"Earliest release date: {df['Release date'].min()}")

reference_date = df['Release date'].min()
df['Game Age (Days)'] = (df['Release date'] - reference_date).dt.days
median_age = df['Game Age (Days)'].median()

print(f"Number of missing values in 'Release date': {df['Release date'].isnull().sum()}")

print(f"Median game age: {median_age} days")
df.drop(columns=['Release date'], inplace=True, errors='ignore') # No longer needed

print(df['Game Age (Days)'].describe())

Earliest release date: 1997-06-30 00:00:00
Number of missing values in 'Release date': 0
Median game age: 8324.0 days
count    66272.000000
mean      8177.432068
std       1102.109736
min          0.000000
25%       7495.000000
50%       8324.000000
75%       8992.000000
max       9924.000000
Name: Game Age (Days), dtype: float64

For later analysis, for whether indie games are recommended differently from other games

In [54]:
def is_indie(genres):
    return 1 if 'Indie' in genres else 0

df['is_indie'] = df['Genres'].apply(is_indie)

print(f"Number of indie games: {df['is_indie'].sum()}")
print(f"Number of non-indie games: {df['is_indie'].count() - df['is_indie'].sum()}")
print(f"Proportion of indie games: {df['is_indie'].mean():.2%}")

Number of indie games: 47847
Number of non-indie games: 18425
Proportion of indie games: 72.20%

Since range of owners is a "Number - Number", we assign them to a single number instead for easier comparisons later on

In [55]:
print("Ranges of owners")
print(df['Estimated owners'].unique())
sorted_ranges = sorted(
    df['Estimated owners'].unique(),
    key=lambda x: int(x.split(' ')[0])
)
print(sorted_ranges)
ranges = {
    r: i for i, r in enumerate(sorted_ranges, start=1)
}

def convert_owners_to_category(owners):
    return ranges.get(owners, np.nan)

df['Owner range'] = df['Estimated owners'].apply(convert_owners_to_category)
print(df['Owner range'].head())

print(f"Number of unique owner ranges: {df['Owner range'].nunique()}")
df.drop(columns=['Estimated owners'], inplace=True, errors='ignore') # No longer needed

Ranges of owners
['0 - 20000' '50000 - 100000' '20000 - 50000' '200000 - 500000'
 '100000 - 200000' '2000000 - 5000000' '500000 - 1000000'
 '1000000 - 2000000' '20000000 - 50000000' '5000000 - 10000000'
 '10000000 - 20000000' '50000000 - 100000000' '100000000 - 200000000']
['0 - 20000', '20000 - 50000', '50000 - 100000', '100000 - 200000', '200000 - 500000', '500000 - 1000000', '1000000 - 2000000', '2000000 - 5000000', '5000000 - 10000000', '10000000 - 20000000', '20000000 - 50000000', '50000000 - 100000000', '100000000 - 200000000']
0    1
1    1
3    1
4    1
5    3
Name: Owner range, dtype: int64
Number of unique owner ranges: 13

Calculating Ratio of review sentiments for easier comparisons

In [56]:
df['Total Reviews'] = df['Positive'] + df['Negative'] # Adding up total positive and negative reviews
df['Review Ratio'] = np.where(
    df['Total Reviews'] > 0,
    df['Positive'] / df['Total Reviews'],
    0.5 # Assigning 0.5 when there are no reviews to avoid division by zero
)

df.drop(columns=['Positive', 'Negative'], inplace=True, errors='ignore') # No longer needed

Extracting useful information only from language columns, such as whether the game supports english and number of languages

In [57]:
def parse_language_list(lang_str): # Convert string representation of list to actual list
    if isinstance(lang_str, str) and lang_str.startswith('[') and lang_str.endswith(']'):
        try:
            return ast.literal_eval(lang_str)
        except (ValueError, SyntaxError):
            return []
    return []

df['Languages List'] = df['Supported languages'].apply(parse_language_list)

# Extracting the useful information from the language columns
df['Num Languages'] = df['Languages List'].apply(len) # Extracting number of languages from the list
df['Is English Supported'] = df['Languages List'].apply(lambda x: 'English' in x).astype(int) # Creating a binary column for English support

# Drop the intermediate and original language columns
df.drop(columns=['Supported languages', 'Full audio languages', 'Languages List'], inplace=True, errors='ignore')

display(df[['Num Languages', 'Is English Supported']].head())
df['Num Languages'].describe()

   Num Languages  Is English Supported
0              1                     1
1             10                     1
3             11                     1
4              2                     1
5              1                     1

count    66272.000000
mean         3.612129
std          4.960837
min          0.000000
25%          1.000000
50%          1.000000
75%          4.000000
max         39.000000
Name: Num Languages, dtype: float64

Seperating the tags as they're all combined in a single string in the original dataset

In [58]:
# tags = {tags count total.split(,) for tags count total in df['Tags']}
tags = {}
genres = {}
categories = {}

# Converting all tags, genres, and categories to seperate lists
for index, row in df.iterrows():
    tags_list = row['Tags'].split(',')
    genres_list = row['Genres'].split(',')
    categories_list = row['Categories'].split(',')

    for tag in tags_list:
        tag = tag.strip()
        tags[tag] = tags.get(tag, 0) + 1

    for genre in genres_list:
        genre = genre.strip()
        genres[genre] = genres.get(genre, 0) + 1

    for category in categories_list:
        category = category.strip()
        categories[category] = categories.get(category, 0) + 1

# Sorting the dictionaries by count
tags = dict(sorted(tags.items(), key=lambda item: item[1], reverse=True))
genres = dict(sorted(genres.items(), key=lambda item: item[1], reverse=True))
categories = dict(sorted(categories.items(), key=lambda item: item[1], reverse=True))

# print number of unique values in Categories, Genres, Tags
print("Unique values in Categories:")
print(len(categories))
print("Unique values in Genres:")
print(len(genres))
print("Unique values in Tags:")
print(len(tags))

# remove Indie from genre and tags since not useful
tags.pop('Indie', None)
genres.pop('Indie', None)

print("Top 30 Tags:")
for tag, count in list(tags.items())[:30]:
    print(f"{tag}: {count}")

print()
print("Top 30 Genres:")
for genre, count in list(genres.items())[:30]:
    print(f"{genre}: {count}")

print()
print("Top 30 Categories:")
for category, count in list(categories.items())[:30]:
    print(f"{category}: {count}")

Unique values in Categories:
41
Unique values in Genres:
34
Unique values in Tags:
452
Top 30 Tags:
Singleplayer: 35664
Action: 30009
Casual: 28736
Adventure: 28219
2D: 18772
Strategy: 14336
Simulation: 14152
RPG: 12651
Puzzle: 12072
Atmospheric: 11997
3D: 11239
Early Access: 9852
Pixel Graphics: 9829
Story Rich: 9680
Colorful: 9617
Exploration: 8816
Cute: 8756
First-Person: 8424
Arcade: 8238
Multiplayer: 8165
Fantasy: 8161
Funny: 7147
Shooter: 6989
Horror: 6782
Retro: 6774
Platformer: 6715
Anime: 6413
Family Friendly: 6411
Sci-fi: 6379
Action-Adventure: 6274

Top 30 Genres:
Action: 28731
Casual: 26622
Adventure: 26514
Simulation: 13399
Strategy: 13330
RPG: 11954
Early Access: 8353
Free to Play: 3484
Sports: 3167
Racing: 2570
Massively Multiplayer: 1632
Violent: 512
Gore: 304
Utilities: 258
Design & Illustration: 155
Animation & Modeling: 132
Nudity: 116
Sexual Content: 105
Education: 98
Video Production: 69
Game Development: 66
Audio Production: 62
Software Training: 54
Web Publishing: 38
Photo Editing: 35
Accounting: 8
Movie: 2
Documentary: 1
Episodic: 1
Short: 1

Top 30 Categories:
Single-player: 63281
Steam Achievements: 32989
Steam Cloud: 17647
Full controller support: 14824
Multi-player: 13286
Steam Trading Cards: 9661
Partial Controller Support: 9164
PvP: 8106
Co-op: 6795
Steam Leaderboards: 6181
Online PvP: 5761
Remote Play Together: 5550
Shared/Split Screen: 5036
Online Co-op: 3765
Shared/Split Screen PvP: 3563
Stats: 3292
Family Sharing: 3020
Shared/Split Screen Co-op: 2921
Remote Play on TV: 2103
Cross-Platform Multiplayer: 1943
Includes level editor: 1822
Steam Workshop: 1782
In-App Purchases: 1461
Captions available: 1122
Remote Play on Tablet: 920
MMO: 863
Remote Play on Phone: 764
LAN PvP: 574
LAN Co-op: 527
VR Only: 388

Applying one-hot encoding to these tags

In [59]:
# one hot encoding first 100 tags, genres top 11, categories top 31
tags_to_encode = list(tags.keys())
genres_to_encode = list(genres.keys())
categories_to_encode = list(categories.keys())

# One-hot encoding the top tags, genres, and categories
def one_hot(column, vocab):
    data = { # True/False mask for every (row, token) pair, returned as a DataFrame
        tok: column.apply(lambda s, t=tok: int(t in s))
        for tok in vocab
    }
    data = {f"{column.name}_{tok}": col for tok, col in data.items()} # Adding prefix to differentiate the columns
    return pd.DataFrame(data, index=column.index)

# Build three separate blocks
tags_block = one_hot(df["Tags"], tags_to_encode)
genres_block = one_hot(df["Genres"], genres_to_encode)
cats_block = one_hot(df["Categories"], categories_to_encode)

df = pd.concat( # Concatenate the original DataFrame with the one-hot encoded blocks
        [df.drop(columns=["Tags", "Genres", "Categories"], errors="ignore"),
         tags_block, genres_block, cats_block],
        axis=1,
        copy=False 
    )

Assign total number of times a developer or publisher has a game on steam

In [60]:
for col in ['Developers', 'Publishers']:
    if col in df.columns:
        # Calculate frequency of each column
        frequency_map = df[col].value_counts()

        # Map the frequency to the column
        df[f'{col} freq'] = df[col].map(frequency_map)

        display(df[[f'{col} freq']].head())

   Developers freq
0                1
1                4
3                1
4                1
5                1

   Publishers freq
0                1
1                5
3                1
4                1
5                1

Finally, saving the dataset

In [61]:
# Final DataFrame Overview
print(f"Final DataFrame shape: {df.shape}")
print(df.dtypes.value_counts())

final_missing = df.isnull().sum().sum()
print(f"Total missing values in final DataFrame: {final_missing}")

df.to_csv('Dataset/games_Cleaned.csv', index=False, encoding='utf-8') # Save the cleaned DataFrame to a new CSV file

Final DataFrame shape: (66272, 550)
int64      540
object       4
bool         3
float64      2
int32        1
dtype: int64
Total missing values in final DataFrame: 0